example submission of liu: 10.15227/orgsyn.095.0080
open-reaction-database/ord-data pull request #50
Opened 2021-01-18 15:16 UTC by ipendlet

Generated using a slightly extended version of the jupyter notebook code from https://github.com/open-reaction-database/ord-schema/tree/main/examples/3_Liu_Copper_OrgSyn.

2021-01-19 16:58 UTC, skearnes commented
Thanks Ian!

* Adding @connorcoley to review since he wrote the original notebook.
* Adding @brilee for "shadow" review.

2021-01-19 23:22 UTC, connorcoley requested changes
Thanks for filling out this example! I've made a couple _very minor_ comments in-line.

I have one larger suggestion, which will actually be very helpful to test an aspect of the schema that isn't often used. For the second and third reactions, we use the pivaloylhyodroxylamine product from the first reaction. This component appropriately has type "SYNTHESIZED" as its preparation in both cases. However, we can be even more explicit and add a reference to the specific reaction that produced it. To do this, you should be able to give the first reaction a placeholder string in its ID field and refer to that in the SYNTHESIZED preparation. Upon submission, when validating the whole dataset, the script should automatically update that cross-reference with the newly-assigned reaction ID. Would you be willing to give that a shot?

2021-01-19 23:22 UTC, connorcoley commented on 2021-01-18_Liu_reactions.pbtxt
> +          mass {
Could potentially add a precision of 0.25 gram here

2021-01-19 23:22 UTC, connorcoley commented on 2021-01-18_Liu_reactions.pbtxt
> +    details: "reaction started in ice bath before addition of\npivaloyl chloride, then allowed to warm to 23 C, then stirred for \'\nan additional 6 hours at RT (23 degC)"
Looks like there is a stray quotation mark here. The newline symbols `\n` aren't ideal for these long, multi-line strings.

2021-01-19 23:22 UTC, connorcoley commented on 2021-01-18_Liu_reactions.pbtxt
> +      person {
You should update this to include yourself! If you'd like to keep both of us, then you can add a "RecordModified" event

2021-01-19 23:22 UTC, connorcoley commented on 2021-01-18_Liu_reactions.pbtxt
> +        name: "Connor W. Coley"
Same comment as above re: provenance

2021-01-19 23:22 UTC, connorcoley commented on 2021-01-18_Liu_reactions.pbtxt
> +        name: "Connor W. Coley"
Same comment

2021-02-16 17:28 UTC, skearnes commented
Hi @ipendlet, it's been a while since the last activity on this PR. Do you have any questions we can answer?

2021-02-19 19:54 UTC, closed without merging